#!/usr/bin/php
<?php

include('miner.inc.php');
include('settings.inc.php');

if(!$settings['donateEnable']){
	echo "Donation disabled \n";
	exit;
}
if(empty($settings['donateAmount'])){
	echo "Error: Wrong settings \n";
	exit;
}
if(!empty($settings['donation'])){
	echo "Warning: Old settings \n";
}

echo time()."\n";

if ($settings['donateAmount'] > 0 and date('H') == 00) {
	$miner = "/opt/minepeon/etc/miner.conf";
	$donate = "/opt/minepeon/etc/miner.conf.donate";
	$original = "/opt/minepeon/etc/miner.conf.orig";
	
	echo "Start   Amount: ".$settings['donateAmount']."\n";

	// Take your miner info and backup
	copy($miner, $original);
	
	// Restart using donation pools
	copy($donate, $miner);
	cgminer("quit", "");
	
	// Switch back to your pools after x minutes
	sleep($settings['donateAmount'] * 60);
	copy($original, $miner);
	cgminer("quit", "");
	echo "Finish !";
}



// stratum.ozco.in:3333 minepeon.donate	donate
// stratum.btcguild.com:3333 MinePeon_Donate MinePeon_Donate
// pool.50btc.com:8332 	Donate
